services:
  # PHP-FPM Service
  php:
    build:
      context: ./php
    container_name: kids_nexus_php_dev
    volumes:
      # Use relative path with :delegated flag
      - .:/var/www/html:delegated
    working_dir: /var/www/html
    environment:
      ENVIRONMENT: dev
      VITE_HOST: https://localhost:5173
    depends_on:
      - db
    networks:
      - kidsnexusnet_dev

  # Nginx Service
  nginx:
    image: nginx:latest
    container_name: kids_nexus_nginx_dev
    volumes:
      # Use relative path with :delegated flag
      - .:/var/www/html:delegated
      # Map your local Nginx config files
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/sites:/etc/nginx/conf.d:ro
      # Mount SSL certificates
      - ./nginx/ssl:/etc/nginx/ssl:ro
    ports:
      - "80:80" # Use standard port 80 for the web server
      - "443:443" # Enable HTTPS
    depends_on:
      - php
    networks:
      - kidsnexusnet_dev

  # MariaDB Service
  db:
    image: mariadb:latest
    container_name: kids_nexus_db_dev
    volumes:
      - db_data_dev:/var/lib/mysql # Use a dev-specific volume
    env_file:
      - .env # Make sure you have a .env file in your project root
    environment:
      # These will be read from your .env file
      MARIADB_ROOT_PASSWORD: ${ROOT_DB_PASS}
      MARIADB_DATABASE: ${DB_NAME}
      MARIADB_USER: ${DB_USER}
      MARIADB_PASSWORD: ${DB_PASS}
    ports:
      - "3307:3306" # Keep this mapping to avoid conflicts if needed
    networks:
      - kidsnexusnet_dev

  # phpMyAdmin Service
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: kids_nexus_phpmyadmin_dev
    restart: always
    ports:
      - "8081:80" # Also keep direct access through port 8081
    environment:
      PMA_HOST: db # Connects to the 'db' service
    depends_on:
      - db
    networks:
      - kidsnexusnet_dev

  # Node/Vite Frontend Dev Server
  node:
    image: node:latest # Or a specific Node version
    container_name: kids_nexus_node_dev
    working_dir: /var/www/html
    volumes:
      # Use relative path with :delegated flag
      - .:/var/www/html:delegated
      # Use a named volume for node_modules to prevent file watching on heavy directories
      - node_modules:/var/www/html/node_modules
    ports:
      - "5173:5173" # Expose Vite's default port
    # Run install and then start the dev server
    command: sh -c "npm install && npm run dev"
    networks:
      - kidsnexusnet_dev

# Define named volumes for data persistence (dev-specific)
volumes:
  db_data_dev:
  node_modules:

# Define the network (dev-specific)
networks:
  kidsnexusnet_dev:
    driver: bridge
